### ISSUE TITLE
How about a release?

### ISSUE THREAD

**Issue by jeacott** [bringking/requirejs-maven-plugin#15]
so the latest version in the maintainers repo has support for Nashorn, but there is no release.
and it seems https://github.com/Vegard-/requirejs-maven-plugin/commits/master  is well ahead of the official maintainers version with rhino 64k error fixed and other tweaks.

please pull available updates and release a new version to maven central. a tag/release in github would be great too.

**Comment by JonMcPherson** [comment]
Yes, please release version 2.0.6 on the maven central repository.  The configuration example in the README doesn't work out of the box because it is for 2.0.6, and only versions 2.0.2 and 2.0.4 are in the maven central repository.  Is version 2.0.6 hosted in a different repository? If so, I would greatly appreciate a link.

**Comment by bringking** [comment]
@jeacott and @JonMcPherson, I am no longer using or maintaining this plugin. Deploying to maven central takes a bit of time, and I am just not equipped to deal with it anymore. I apologize, and I would be happy to help someone get spun up any way that I can.
